### ISSUE TITLE
Include fixes from other forks

### ISSUE THREAD

**Issue by PetarKirov** [elecnix/screenkey#7]
From a user's point of view, the number of [forks](https://github.com/scs3jb/screenkey/network) it is really confusing because it is not clear which version to choose. Almost every fork has some fixes that the others don't have. Since you [branched](https://github.com/elecnix/screenkey/tree/c3e3cf981b055ffc806e2959a230e14bdc897340) from @seletskiy's fork, would you be OK with making a merge request to his [repo](https://github.com/seletskiy/screenkey), so there can be a single source of truth?

Or at least merge his [changes](https://github.com/elecnix/screenkey/compare/master...seletskiy:master) to your repo?

**Comment by seletskiy** [comment]
@ZombineDev: consider using rewritten version, it's much better: https://github.com/wavexx/screenkey

**Comment by PetarKirov** [comment]
@seletskiy Thanks for the heads up! I didn't know about it.
@elecnix Sorry for the noise. Closing this issue as it is now irrelevant.
